DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
user_id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR ,
username VARCHAR(50) NOT NULL ,
email VARCHAR(50) NOT NULL,
password VARCHAR(120) NOT NULL,
roleId INT NOT NULL FOREIGN KEY
);

DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES (
role_id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(20) NOT NULL
);